services:
  db:
    image: postgres:15 # Updated from postgres:13 to postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678" # For debugging
    environment:
      - PYTHONUNBUFFERED=1
      - REACT_DEVELOPMENT_URL=http://frontend:3000
    command: sh /app/start.sh

  frontend:
    build:
      context: ./frontend
      target: build # Use the build stage to build the React app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
      - WDS_SOCKET_PORT=3000 # Adding this for WebSockets in React development
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  postgres_data:
